// Mocks generated by Mockito 5.2.0 from annotations
// in capstone_project/test/api/auth_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:capstone_project/api/auth_service.dart' as _i2;
import 'package:capstone_project/Model/Login/Request/login_model.dart' as _i7;
import 'package:capstone_project/Model/Login/Response/login_response.dart'
    as _i6;
import 'package:capstone_project/Model/Register/Request/register_model.dart'
    as _i5;
import 'package:capstone_project/Model/Register/Response/register_response.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.RegisterResponse?> register(_i5.RegisterModel? pModel) =>
      (super.noSuchMethod(Invocation.method(#register, [pModel]),
              returnValue: Future<_i4.RegisterResponse?>.value())
          as _i3.Future<_i4.RegisterResponse?>);
  @override
  _i3.Future<_i6.LoginResponse?> login(_i7.LoginModel? lModel) =>
      (super.noSuchMethod(Invocation.method(#login, [lModel]),
              returnValue: Future<_i6.LoginResponse?>.value())
          as _i3.Future<_i6.LoginResponse?>);
  @override
  _i3.Future<_i6.LoginResponse?> forgotPass(_i7.LoginModel? lModel) =>
      (super.noSuchMethod(Invocation.method(#forgotPass, [lModel]),
              returnValue: Future<_i6.LoginResponse?>.value())
          as _i3.Future<_i6.LoginResponse?>);
}
