// Mocks generated by Mockito 5.2.0 from annotations
// in capstone_project/test/api/user_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:capstone_project/api/user_service.dart' as _i5;
import 'package:capstone_project/Model/Profile/request_password.dart' as _i8;
import 'package:capstone_project/Model/Profile/request_profile.dart' as _i7;
import 'package:capstone_project/Model/Profile/response_profile.dart' as _i4;
import 'package:capstone_project/Model/userdata/history_model.dart' as _i3;
import 'package:capstone_project/Model/userdata/user_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUserModel_0 extends _i1.Fake implements _i2.UserModel {}

class _FakeHistoryModel_1 extends _i1.Fake implements _i3.HistoryModel {}

class _FakeResProfileModel_2 extends _i1.Fake implements _i4.ResProfileModel {}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i5.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.UserModel> getUser() =>
      (super.noSuchMethod(Invocation.method(#getUser, []),
              returnValue: Future<_i2.UserModel>.value(_FakeUserModel_0()))
          as _i6.Future<_i2.UserModel>);
  @override
  _i6.Future<_i3.HistoryModel> getHistory() => (super.noSuchMethod(
          Invocation.method(#getHistory, []),
          returnValue: Future<_i3.HistoryModel>.value(_FakeHistoryModel_1()))
      as _i6.Future<_i3.HistoryModel>);
  @override
  _i6.Future<_i4.ResProfileModel> editProfile(
          _i7.ReqEditProfileModel? setData) =>
      (super.noSuchMethod(Invocation.method(#editProfile, [setData]),
              returnValue:
                  Future<_i4.ResProfileModel>.value(_FakeResProfileModel_2()))
          as _i6.Future<_i4.ResProfileModel>);
  @override
  _i6.Future<_i4.ResProfileModel> editPassword(_i8.ReqEditPassModel? setData) =>
      (super.noSuchMethod(Invocation.method(#editPassword, [setData]),
              returnValue:
                  Future<_i4.ResProfileModel>.value(_FakeResProfileModel_2()))
          as _i6.Future<_i4.ResProfileModel>);
}
